### ISSUE TITLE
Add basic cargo support

### ISSUE THREAD

**Issue by klusoga** [klusoga-software/shelf#6]
```[tasklist]
### Tasks
- [ ] https://github.com/klusoga-software/shelf/issues/7
- [ ] https://github.com/klusoga-software/shelf/issues/8
- [ ] https://github.com/klusoga-software/shelf/issues/9
```
